name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Boost (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      - name: Install Boost (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install boost-msvc-14.3 -y

      - name: Configure CMake
        run: cmake -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: cmake --build build --target test --config Release

      - name: Package
        run: cmake --build build --target package --config Release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' # Релиз создается только при пуше в main
        with:
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            build/*.deb
            build/*.zip