name: 'C++ CI'

on:
  push:
    branches:
      - main
      - lab-1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
        
      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        run: vcpkg install boost-test
        
      - name: Configure CMake Linux
        if: matrix.os != 'windows-latest'
        run: "cmake -B build -DPATCH_VERSION=${{ github.run_number }} \
              -DCMAKE_BUILD_TYPE=Release"
              
      - name: Configure CMake Windows
        if: matrix.os == 'windows-latest'
        run: "cmake -B build -DPATCH_VERSION=${{ github.run_number }} \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C Release --output-on-failure

      - name: Package
        run: cmake --build build --config Release --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: |
            build/*.deb
            build/*.msi
            build/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.${{ github.run_number }}
          name: Release 0.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/packages-ubuntu-latest/*
            ./artifacts/packages-windows-latest/*